# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: trailing-whitespace

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    # --allow-untyped-decorators because of
    # https://github.com/pytest-dev/pytest/issues/7589
    # *should have* been fixed by https://github.com/python/mypy/pull/9232
    # which was merged a long time ago, but still fails for me
    args: [ '--strict', '--allow-untyped-decorators' ]
    additional_dependencies: [ 'pytest==6.0.2' ]

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.31.0
  hooks:
  - id: yapf

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: remove-crlf
  - id: remove-tabs
    args: [ '--whitespaces-count', '8' ]  # defaults to 4, which is wrong

- repo: local
  hooks:
  - id: clang-format
    name: Code formatting
    language: system
    types_or: [c, c++]
    entry: "clang-format -style=file -i"
