# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: trailing-whitespace

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: remove-crlf
  - id: remove-tabs
    args: [ '--whitespaces-count', '8' ]  # defaults to 4, which is wrong

- repo: local
  hooks:
  - id: clang-format
    name: Code formatting
    language: system
    types_or: [c, c++]
    entry: "clang-format -style=file -i"
