name: build and test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: sudo apt-get -y install clang-tidy
    - name: make
      run: make
    - name: make check
      run: make check
